name: flutter_playground
description: A playground to more understand flutter ecosystem

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  state_provider:
    path: ./learn_state/state_provider
  state_bloc:
    path: ./learn_state/state_bloc

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
